POST http://localhost:5600/login
Content-Type: application/json

{
    "email": "alex00yt@gmail.com",
    "password": "123456789"
}

####

GET http://localhost:5600/admin/activity-log
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTY3Nzc5NjU4ODQ1OSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg0ODk2NTZ9.rgtY2hgirH6NFiHkBYnfsNUY25WHx2gSWk5gjkD8FxI

{
    "id": "1677796588459",
    "email": "alex00yt@gmail.com",
    "role": "admin"
}

####

GET http://localhost:5600/admin
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkIjoiMTY3Nzc5NjU4ODQ1OSIsInJvbGUiOiJhZG1pbiJ9LCJpYXQiOjE2Nzg0ODk2NTZ9.rgtY2hgirH6NFiHkBYnfsNUY25WHx2gSWk5gjkD8FxI

{
    "id": "1677796588459",
    "email": "alex00yt@gmail.com",
    "role": "admin"
}

####

POST http://localhost:5600/activity-log
Content-Type: application/json

{
    "idUser": 2,
    "tipo": "Adoptar"
}


####

POST http://localhost:5600/login
Content-Type: application/json

{
    "email" : "alex00yt@gmail.com",
    "password" : "alex123"
}

####

POST http://localhost:5600/registrar
Content-Type: application/json

{
    "nombre" : "Santiago", 
    "telefono" : "5654789623",
    "email" : "santiolvera03@gmail.com",
    "password" : "santi123",
    "passwordConf" : "santi123"
}

####

POST http://localhost:5600/login
Content-Type: application/json

{
    "email" : "santiolvera03@gmail.com",
    "password" : "santi123"
}

###
POST http://localhost:5500/logout?_method=DELETE